# write a docker compose that build an image called my-apache2 and that link my port 8080 to 80

version: '3.8'

services:
  app:
    container_name: web_app
    image: web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
